"""
Infowars Extravaganza Generator - Creates standalone player with RSS feed integration
"""

import os
import shutil
from pathlib import Path
from datetime import datetime
from typing import Dict, Optional, Any
import logging

logger = logging.getLogger(__name__)

class InfowarsExtravaganzaGenerator:
    """
    Generator for Infowars Extravaganza player - RSS-fed video player
    with red/black/yellow theme and 6-video pagination
    """
    
    def __init__(self):
        self.template_name = "infowars_extravaganza.html"
        self.project_root = Path(__file__).resolve().parent.parent.parent
        self.template_path = self.project_root / "Web_Players" / self.template_name
        self.output_dir = self.project_root / "M3U_Matrix_Output" / "generated_pages"
        self.ready_made_dir = self.project_root / "M3U_Matrix_Output" / "Ready_Made"
        
    def generate(self, output_filename: Optional[str] = None, config: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
        """
        Generate Infowars Extravaganza player page
        
        Args:
            output_filename: Optional custom filename for output
            config: Optional configuration (not used for this RSS-based player)
            
        Returns:
            Dict with generation results
        """
        try:
            # Create output directories
            self.output_dir.mkdir(parents=True, exist_ok=True)
            self.ready_made_dir.mkdir(parents=True, exist_ok=True)
            
            # Generate filename with timestamp
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            
            if not output_filename:
                output_filename = f"infowars_extravaganza_{timestamp}.html"
            elif not output_filename.endswith('.html'):
                output_filename += '.html'
                
            # Check if template exists
            if not self.template_path.exists():
                raise FileNotFoundError(f"Template not found: {self.template_path}")
                
            # Read template content
            with open(self.template_path, 'r', encoding='utf-8') as f:
                content = f.read()
                
            # The template is standalone and fetches RSS dynamically,
            # so we don't need to embed playlist data
            
            # Add generation metadata as HTML comment
            metadata_comment = f"""
<!-- 
    Generated by Infowars Extravaganza Generator
    Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
    RSS Feed: https://rss.infowars.com/hourly/InfowarsHourlyVideo.xml
    Features: 
    - Auto-refresh every hour
    - 6 videos per page pagination
    - Red/Black/Yellow theme
    - Date/time overlays
    - Responsive design
-->
"""
            content = content.replace('<!DOCTYPE html>', f'<!DOCTYPE html>{metadata_comment}')
            
            # Save to generated_pages
            output_path = self.output_dir / output_filename
            with open(output_path, 'w', encoding='utf-8') as f:
                f.write(content)
                
            # Also save to Ready_Made folder for GitHub deployment
            ready_made_path = self.ready_made_dir / output_filename
            with open(ready_made_path, 'w', encoding='utf-8') as f:
                f.write(content)
                
            # Return success info
            return {
                "success": True,
                "output_path": str(output_path),
                "ready_made_path": str(ready_made_path),
                "filename": output_filename,
                "timestamp": timestamp,
                "template": self.template_name,
                "features": [
                    "RSS Feed Integration",
                    "6-Video Pagination", 
                    "Hourly Auto-Refresh",
                    "Red/Black/Yellow Theme",
                    "Date/Time Overlays",
                    "Thumbnail Display",
                    "Mobile Responsive"
                ],
                "message": f"Infowars Extravaganza player generated successfully: {output_filename}"
            }
            
        except Exception as e:
            logger.error(f"Error generating Infowars Extravaganza: {str(e)}")
            return {
                "success": False,
                "error": str(e),
                "message": f"Failed to generate Infowars Extravaganza: {str(e)}"
            }
            
    def generate_with_deploy(self, deploy_to_github: bool = False) -> Dict[str, Any]:
        """
        Generate and optionally deploy to GitHub
        
        Args:
            deploy_to_github: Whether to trigger GitHub deployment
            
        Returns:
            Generation results
        """
        result = self.generate()
        
        if result["success"] and deploy_to_github:
            try:
                # Import GitHub deployer if available
                import sys
                sys.path.insert(0, str(self.project_root / "Core_Modules"))
                from github_deploy import GitHubDeployer
                
                deployer = GitHubDeployer()
                deploy_result = deployer.deploy_file(
                    result["ready_made_path"],
                    f"Deploy Infowars Extravaganza - {result['timestamp']}"
                )
                
                result["github_deployed"] = deploy_result.get("success", False)
                result["github_url"] = deploy_result.get("url", "")
                
            except ImportError:
                result["github_deployed"] = False
                result["github_error"] = "GitHub deployer not available"
            except Exception as e:
                result["github_deployed"] = False
                result["github_error"] = str(e)
                
        return result


# CLI usage
if __name__ == "__main__":
    import argparse
    
    parser = argparse.ArgumentParser(description="Generate Infowars Extravaganza Player")
    parser.add_argument('--output', '-o', help='Output filename')
    parser.add_argument('--deploy', '-d', action='store_true', help='Deploy to GitHub')
    
    args = parser.parse_args()
    
    generator = InfowarsExtravaganzaGenerator()
    
    if args.deploy:
        result = generator.generate_with_deploy(deploy_to_github=True)
    else:
        result = generator.generate(output_filename=args.output)
        
    if result["success"]:
        print(f"✅ {result['message']}")
        print(f"📁 Output: {result['output_path']}")
        print(f"📁 Ready Made: {result['ready_made_path']}")
        if result.get("github_deployed"):
            print(f"🌐 GitHub: {result.get('github_url', 'Deployed')}")
    else:
        print(f"❌ {result['message']}")